function Flag_CustomPlot(){
	with(Flag_GetStorage(FLAG_PLOT)){
		Set("floweyroom_meetflowey",0);
		Set("ruins_0_flowey",0);
		Set("ruins_1_door",0);
		Set("ruins_2_open",0);
		Set("ruins_3_flowey",0);
		Set("ruins_3_dummy",0);
		Set("ruins_6_open",0);
		Set("ruins_7_open",0);
		Set("ruins_8_bread",0);
		Set("ruins_9_open",0);
		Set("ruins_10_stonecandy_number",5);
		Set("ruins_11_1_goggles",0);
		Set("ruins_12_fall",0);
		Set("ruins_13_1_tifency",0);
		Set("ruins_13_1_tifency_question",[6,0,1,2,3]);
		Set("ruins_13_1_tifency_question_new",[]);
		Set("ruins_13_1_tifency_question_chose",[]);
		Set("ruins_14_door",0);
		Set("ruins_15_tifency_dialog",0);
		Set("ruins_16_open",0);
		Set("ruins_16_1_open",0);
		Set("ruins_16_2_open",0);
		Set("ruins_16_3_lever",0);
		Set("ruins_17_trial",0);
		Set("ruins_17_1_lever",0);
		Set("ruins_18_1_camera",0);
		Set("ruins_18_4_lever",0);
		Set("ruins_18_3_greedish",0);
	}
}